# Generated by Django 3.0.1 on 2020-01-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='address',
            new_name='wallet',
        ),
        migrations.AddField(
            model_name='account',
            name='addreed_to_rules',
            field=models.BooleanField(default=True),
        ),
    ]
